colorscheme dracula

# Kill trailing whitespace.
hook global BufWritePre ^[^*].* %{
    try %{ execute-keys -draft \%s\h+$<ret>d }
}

# Copied from Benjamin.
set-option global idle_timeout 500
set-option global indentwidth 2
set-option global scrolloff 3,6
set-option global tabstop 2
