#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Jared Norman"
email = "jared@super.gd"

[ui]
default-command = "log"
diff-editor = ":builtin"

# Defaults: https://github.com/jj-vcs/jj/blob/main/cli/src/config/colors.toml
[colors]
"rest" = "#bcc5cf"

"commit_id" = "blue"
"working_copy commit_id" = "blue"

"change_id" = "green"
"working_copy change_id" = "green"

"author" = "#8790a0"
"working_copy author" = "#8790a0"

"timestamp" = "#bac3cb"
"working_copy timestamp" = "#8790a0"

"bookmarks" = "yellow"
"working_copy bookmarks" = "yellow"

"description placeholder" = "magenta"
"working_copy description placeholder" = "magenta"

"empty description placeholder" = "#bac3cb"
"working_copy empty description placeholder" = "#bac3cb"

"empty" = "magenta"
"working_copy empty" = "magenta"

[aliases]
bm = ["bookmark"]

[git]
private-commits = '''description('private:*')'''
